version: "3"
services:
  web:
    container_name: node_web
    build: .
    command: ["npm", "run", "dev:debug"]
    ports:
      - "8088:80"
      - "9229:9229"
    networks:
      - webnet
    volumes:
      - .:/app
  redis:
    container_name: redis_primary
    image: "redis:alpine"
    networks:
      - webnet
    volumes:
      - ./data:/data
networks:
  webnet:
