version: "3"
services:
  web:
    image: andregeng/node-docker-demo:v2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8088:80"
    networks:
      - webnet
  redis:
    image: "redis:alpine"
networks:
  webnet:
