version: "3"
services:
  web:
    container_name: node_web
    image: andregeng/node-docker-demo:v2
    ports:
      - "8088:80"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  redis:
    image: "redis:alpine"
    networks:
      - webnet
    volumes:
      - ./data:/data
networks:
  webnet:
